'''
editor的一些可设置的参数
'''


class EditorConfig:
    EDITOR_SCENE_BACKGROUND_COLOR = '#212121'
    EDITOR_SCENE_GRID_NORMAL_LINE_COLOR = '#313131'
    EDITOR_SCENE_GRID_DARK_LINE_COLOR = '#151515'

    EDITOR_SCENE_GRID_NORMAL_LINE_WIDTH = 1.0
    EDITOR_SCENE_GRID_DARK_LINE_WIDTH = 1.5

    EDITOR_SCENE_GRID_SIZE = 20
    EDITOR_SCENE_GRID_CHUNK = 10

    EDITOR_SCENE_WIDTH = 32000
    EDITOR_SCENE_HEIGHT = 32000

    EDITOR_NODE_TITLE_FONT_SIZE = 14
    EDITOR_NODE_TITLE_FONT = 'Microsoft YaHei'
    EDITOR_NODE_PIN_LABEL_FONT_SIZE = 12
    EDITOR_NODE_PIN_LABEL_FONT = 'Microsoft YaHei'

    PORT_ICON_SIZE = 20
